Remove redundant as names from imports
gleam-lang/gleam pull request #2989
Opened 2024-04-14 13:55 UTC by giacomocavalieri

As suggested by @jfmengels the formatter could remove redundant as names in imports:
```gleam
import gleam/int as int
//               ^^^^^^ Redundant and removed by the formatter
```

2024-04-15 10:14 UTC, lpil approved these changes
Very nice! Thank you.

2024-04-15 22:33 UTC, hamirmahal requested changes

2024-04-15 22:33 UTC, hamirmahal commented on compiler-core/src/format.rs
> +                    //                  ^^^^^^ this is redundand and removed
```suggestion
                    //                  ^^^^^^ this is redundant and removed
```

2024-04-16 13:17 UTC, giacomocavalieri commented on compiler-core/src/format.rs
> +                    //                  ^^^^^^ this is redundand and removed
Nice catch! Thank you

2024-04-16 22:34 UTC, lpil commented
Could you rebase on main please? Also note I'm trying a new changelog format!

2024-04-17 11:19 UTC, lpil approved these changes
Thank you!

2024-04-17 11:20 UTC, merged